spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/event_api'
    username: event_api_user01
    password: 'CHANGE_ME_TO_SECURE_PASSWORD'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://konturlabs.us.auth0.com/'
auth0:
  audience: 'https://test-apps02.konturlabs.com/events/'

pdc:
  host: 'https://testemops.pdc.org'
  user: user
  password: password

scheduler:
  hpSrvImport:
    enable: true
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  eventCombination:
    enable: true
    initialDelay: 10000
    fixedDelay: 60000
  feedComposition:
    enable: true
    initialDelay: 20000
    fixedDelay: 60000
