spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/event_api'
    username: event_api_user01
    password: 'CHANGE_ME_TO_SECURE_PASSWORD'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://konturlabs.us.auth0.com/'
auth0:
  audience: 'https://test-apps02.konturlabs.com/events/'

konturApi:
  host: 'https://api.kontur.io/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'
  user: user
  password: password

stormsImport:
  host: 'https://www1.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/'

tornadoJapanMa:
  host: 'https://www.data.jma.go.jp/obd/stats/data/bosai/tornado/'

scheduler:
  hpSrvImport:
    enable: false
    initialDelay: 1000
  hpSrvMagsImport:
    enable: true
    initialDelay: 10000
    fixedDelay: 600000
  pdcMapSrvSearch:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  gdacsImport:
    enable: true
    cron: 30 0/5 * * * *
  firmsImport:
    enable: true
  emDatImport:
    enable: true
  staticImport:
    enable: true
    initialDelay: 1000
  stormsNoaaImport:
    enable: true
    initialDelay: 1000
    fixedDelay: P1D
  tornadoJapanMaImport:
    enable: false
    initialDelay: 1000
    fixedDelay: P1D
  historicalTornadoJapanMaImport:
    enable: false
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000
  eventCombination:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000
  feedComposition:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000
    alias: gdacs, em-dat, pdc-v0, swissre-02
  firmsFeedComposition:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000
    alias: firms

aws:
  sqs:
    enabled: true
    url: https://sqs.us-west-1.amazonaws.com/001426858141/SNS_messages_from_pdc-test-publiccloud-sns.fifo