spring:
  datasource:
    url: 'URL'
    username: 'USERNAME'
    password: 'PASSWORD'
  profiles:
    active: 'dev | test | prod'

pdc:
  user: 'PDC_USER'
  password: 'PDC_PASSWORD'

emdat:
  user: 'EM_DAT_USER'
  password: 'EM_DAT_PASSWORD'

aws:
  sqs:
    url: 'AWS_SQS_URL'