server:
  port: 8624

spring:
  datasource:
    platform: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'

pdc:
  host: 'https://testemops.pdc.org'
  user: 'user'
  password: 'password'

scheduler:
  hpSrvImport:
    enable: true
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  recombination:
    enable: true
    initialDelay: 10000
    fixedDelay: 60000

feign:
  client:
    config:
      pdcHpSrvBasicAuth:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: headers
        requestInterceptors:
          - feign.auth.BasicAuthRequestInterceptor

mybatis:
  config-location: classpath:mybatis-config.xml
  type-handlers-package: io.kontur.eventapi.typehandler
