server:
  port: 8624

auth0:
  audience: https://test-apps02.konturlabs.com/events/

spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://konturlabs.us.auth0.com/

pdc:
  host: 'https://testemops.pdc.org'
  user: 'eventapi'
  password: 'zvgusf48D'

scheduler:
  hpSrvImport:
    enable: true
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  eventCombination:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  feedComposition:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000

feign:
  client:
    config:
      pdcHpSrvBasicAuth:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: headers
        requestInterceptors:
          - feign.auth.BasicAuthRequestInterceptor

mybatis:
  mapper-locations: classpath:db/mappers/*Mapper.xml
  type-handlers-package: io.kontur.eventapi.typehandler

springdoc:
  swagger-ui:
    path: 'doc'
    disable-swagger-default-url: true