spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5433/postgres'
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/auth/realms/zigzag
          jwk-set-uri: https://keycloak01.konturlabs.com/auth/realms/zigzag/protocol/openid-connect/certs

konturApi:
  host: 'https://test-api02.konturlabs.com/'

konturApps:
  host: 'https://test-apps02.konturlabs.com/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'

staticdata:
  s3Folder: 'TEST DEV/'


scheduler:
  hpSrvImport:
    enable: false
  hpSrvMagsImport:
    enable: false
  pdcMapSrvSearch:
    enable: false
  gdacsImport:
    enable: false
  firmsImport:
    enable: false
  emDatImport:
    enable: false
  staticImport:
    enable: false
  stormsNoaaImport:
    enable: false
  tornadoJapanMaImport:
    enable: false
  historicalTornadoJapanMaImport:
    enable: false
  normalization:
    enable: true
  eventCombination:
    enable: true
  feedComposition:
    enable: true
  enrichment:
    enable: false
  calfireSearch:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000

aws:
  sqs:
    enabled: false