server:
  port: 8624

spring:
  datasource:
    platform: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'

pdc:
  host: 'https://testemops.pdc.org'
  user: 'sanych'
  password: '111111'

app:
  scheduler:
    hpSrvImport:
      initialDelay: 1000
      fixedDelay: 600000000
#      fixedDelay: 600000

feign:
  client:
    config:
      pdcHpSrvBasicAuth:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: headers
        requestInterceptors:
          - feign.auth.BasicAuthRequestInterceptor