server:
  servlet:
    contextPath: /events
  port: 8624

auth0:
  audience: https://test-apps02.konturlabs.com/events/

spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      minimum-idle: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://konturlabs.us.auth0.com/
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

pdc:
  host: 'https://testemops.pdc.org'
  user: 'eventapi'
  password: 'zvgusf48D'

gdacs:
  host: 'https://www.gdacs.org'

emdat:
  user: 'username'
  password: 'password'
  host: 'https://public.emdat.be/api'

konturApi:
  host: 'https://api.kontur.io/'

scheduler:
  hpSrvImport:
    enable: false
    initialDelay: 1000
  hpSrvMagsImport:
    enable: false
    initialDelay: 10000
    fixedDelay: 600000
  gdacsImport:
    enable: true
    cron: 30 0/5 * * * *
  firmsImport:
    enable: true
    initialDelay: 1000
    fixedDelay: 3600000
  emDatImport:
    enable: true
    initialDelay: 1000
    fixedDelay: PT3H # every 3 hours
  staticTornadoImport:
    enable: true
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  eventCombination:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  feedComposition:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: headers
      pdcHpSrvBasicAuth:
        requestInterceptors:
          - feign.auth.BasicAuthRequestInterceptor

mybatis:
  mapper-locations: classpath:db/mappers/*Mapper.xml
  type-handlers-package: io.kontur.eventapi.typehandler

springdoc:
  swagger-ui:
    path: 'doc'
    disable-swagger-default-url: true

aws:
  sqs:
    enabled: false
    url: https://sqs.us-west-1.amazonaws.com/001426858141/SNS_messages_from_pdc-test-publiccloud-sns.fifo

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
