server:
  servlet:
    contextPath: /events
  port: 8624
  jetty:
    connection-idle-timeout: 3600000

spring:
  datasource:
    platform: postgres
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    hikari:
      register-mbeans: true
      pool-name: HikariPool-1
      minimum-idle: 8
      maximum-pool-size: 16
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 600000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak01.konturlabs.com/auth/realms/zigzag
          jwk-set-uri: https://keycloak01.konturlabs.com/auth/realms/zigzag/protocol/openid-connect/certs
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  profiles:
    active: awsSqsDisabled, jwtAuthDisabled


konturApi:
  host: 'https://test-api02.konturlabs.com/'

konturApps:
  host: 'https://test-apps02.konturlabs.com/'

pdc:
  host: 'https://testemops.pdc.org'
  mapSrvHost: 'https://testapps.pdc.org'
  user: 'eventapi'
  password: 'zvgusf48D'

gdacs:
  host: 'https://www.gdacs.org'

emdat:
  user: 'username'
  password: 'password'
  host: 'https://public.emdat.be/api'

stormsNoaa:
  host: 'https://www1.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/'

staticdata:
  s3Bucket: 'event-api-locker01'
  s3Folder: 'EXP/'

tornadoJapanMa:
  host: 'https://www.data.jma.go.jp/obd/stats/data/bosai/tornado/'

scheduler:
  hpSrvImport:
    enable: false
    initialDelay: 1000
  hpSrvMagsImport:
    enable: false
    initialDelay: 10000
    fixedDelay: 600000
  pdcMapSrvSearch:
    enable: true
    initialDelay: 1000
    fixedDelay: 60000
  gdacsImport:
    enable: true
    cron: 0 1/5 * * * * # every five minutes after hh:01:00
  firmsImport:
    enable: true
    initialDelay: 1000
    fixedDelay: 3600000
  emDatImport:
    enable: true
    initialDelay: 1000
    fixedDelay: PT3H # every 3 hours
  staticImport:
    enable: true
    initialDelay: 1000
  stormsNoaaImport:
    enable: true
    initialDelay: 1000
    fixedDelay: P1D # every day
  tornadoJapanMaImport:
    enable: false
    initialDelay: 1000
    fixedDelay: P1D
  historicalTornadoJapanMaImport:
    enable: false
    initialDelay: 1000
  normalization:
    enable: true
    initialDelay: 1000
    fixedDelay: 10000
  eventCombination:
    enable: true
    initialDelay: 1000
    fixedDelay: 10000
    providers:
      em-dat,
      gdacsAlert,
      gdacsAlertGeometry,
      hpSrvMag,
      hpSrvSearch,
      pdcMapSrv,
      pdcSqs,
      tornado.canada-gov,
      tornado.australian-bm,
      tornado.osm-wiki,
      tornado.des-inventar-sendai,
      storms.noaa,
      wildfire.frap.cal,
      wildfire.sa-gov,
      wildfire.qld-des-gov,
      wildfire.victoria-gov,
      wildfire.nsw-gov
    firmsProviders: firms.modis-c6, firms.suomi-npp-viirs-c2, firms.noaa-20-viirs-c2
  feedComposition:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000
    alias: gdacs, em-dat, pdc-v0, swissre-02, kontur-public
    firmsAlias: firms, disaster-ninja-02
  enrichment:
    enable: true
    initialDelay: 1000
    fixedDelay: 1000

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: headers

mybatis:
  mapper-locations: classpath:db/mappers/*Mapper.xml
  type-handlers-package: io.kontur.eventapi.typehandler

springdoc:
  swagger-ui:
    path: 'doc'
    disable-swagger-default-url: true

aws:
  sqs:
    enabled: false
    url: https://sqs.us-west-1.amazonaws.com/001426858141/SNS_messages_from_pdc-test-publiccloud-sns.fifo

management:
  metrics:
    export:
      simple:
        enabled: false
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    refresh:
      enabled: false
  endpoint:
    health:
      status:
        http-mapping:
          down: 200
      cache:
        time-to-live: 10s
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
