--- # Time-stamp: <2022-09-15 20:48:01>

name: 01 Building with Maven

'on':
  - push
  - fork

jobs:
  helper:
    uses: ./.github/workflows/migration-helper01.yml
  build:
    runs-on: ubuntu-latest
    needs: helper
    # strategy:
    #   matrix:
    #     os:
    #       - ubuntu-latest
    # runs-on: '${{ matrix.os }}'
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: corretto
          cache: maven

      - name: Building with Maven
        env:
          MAVEN_CLI_OPTS: '--batch-mode'
          NEXUS_DEPLOYER: ${{ secrets.NEXUS_READER }}
          NEXUS_DEPLOYER_PASS: ${{ secrets.NEXUS_READER_PASS }}
        run: |-
          set -e

          wget -q https://kontur-github-runners.s3.eu-central-1.amazonaws.com/public_resources/projects/common/2022091500.tar.xz && tar -C "$HOME" -xf 2022091500.tar.xz && rm 2022091500.tar.xz

          mvn $MAVEN_CLI_OPTS clean install -U -Prelease
          mv -v target/*.zip .

      - name: Uploading build artifacts
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: 'event-api-${{needs.helper.outputs.CI_COMMIT_REF_SLUG}}'
          path: '*.zip'
          retention-days: 10

      - name: Publishing JUnit Test result report
        uses: konturio/action-junit-report@v3
        if: always()
        with:
          report_paths: target/*-reports/*.xml
          retention-days: 10
